CLASS zcl_abappm_ajson_filter_lib DEFINITION
  PUBLIC
  CREATE PRIVATE.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abappm_ajson_filter_lib IMPLEMENTATION.
ENDCLASS.
