CLASS zcl_abappm_ajson_utilities DEFINITION
  PUBLIC
  CREATE PRIVATE.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abappm_ajson_utilities IMPLEMENTATION.
ENDCLASS.
