CLASS ZCL_ABAPPM_HIGHLIGHTER_TXT DEFINITION
  PUBLIC
  INHERITING FROM ZCL_ABAPPM_HIGHLIGHTER
  CREATE PUBLIC.

  PUBLIC SECTION.

    METHODS process_line REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ABAPPM_HIGHLIGHTER_TXT IMPLEMENTATION.


  METHOD process_line.

    rv_line = apply_style(
      iv_line  = iv_line
      iv_class = '' ).

  ENDMETHOD.
ENDCLASS.
